In [7]:
#Создайте numpyarray с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

import numpy as np
np.arange(9, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [18]:
#Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

N = 10
np.diag(np.arange(N, -1, -1), k=0)


array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [21]:
np.sum(np.diag(np.arange(N, -1, -1), k=0))

55

In [32]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

In [ ]:
#задание3

In [33]:
from numpy import linalg

In [34]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [35]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [ ]:
#задание4
Для датафреймаlog из материалов занятия создайте столбец source_type по следующим правилам:
- если источник traffic_source равен yandex или google, то в source_type ставится organic
- для источников paid и email из России - ставим ad
- для источников paid и email не из России - ставим other
- все остальные варианты берем из traffic_source без изменений

In [36]:
import pandas as pd

In [39]:
log = pd.read_csv('visit_log.csv', sep=';')
log.head(20)

timestamp    visit_id                                 url   region  \
0   1549980692  e3b0c44298  https://host.ru/3c19b4ef7371864fa3   Russia   
1   1549980704  6e340b9cff  https://host.ru/c8d9213a31839f9a3a   Russia   
2   1549980715  96a296d224  https://host.ru/b8b58337d272ee7b15   Russia   
3   1549980725  709e80c884  https://host.ru/b8b58337d272ee7b15   Russia   
4   1549980736  df3f619804  https://host.ru/b8b58337d272ee7b15   Russia   
5   1549980742  8855508aad  https://host.ru/df646c3676cc259fa0   Russia   
6   1549980742  b0f66adc83  https://host.ru/b8b58337d272ee7b15   Russia   
7   1549980754  837885c8f8  https://host.ru/108ce4b365afb7b88e   Russia   
8   1549980760  af5570f5a1  https://host.ru/3004a8273caeef2867    China   
9   1549980765  3e7077fd2f  https://host.ru/df646c3676cc259fa0   Russia   
10  1549980777  01d448afd9  https://host.ru/a5dda93e70318570c0    India   
11  1549980785  71b6c1d538  https://host.ru/c8d9213a31839f9a3a  Ukraine   
12  1549980789  15ec7bf0b5  https://host.ru/8e88d4703848cc0ec4   Russia   
13  1549980792  dd46c3eebb  https://host.ru/3004a8273caeef2867    China   
14  1549980793  e7ecebbc59  https://host.ru/05e41944dd85a900a6  Belarus   
15  1549980797  5322fecfc9  https://host.ru/4adc8a29b212051b04  Belarus   
16  1549980801  374708fff7  https://host.ru/39fa884393666d45fc   Russia   
17  1549980807  0a88111852  https://host.ru/2fcb223266880ccf57  Ukraine   
18  1549980814  60daa3a5f7  https://host.ru/ef57543002ce2a0f2a  Belarus   
19  1549980816  d6fd62f5ce  https://host.ru/f1eb4601740d627ab0  Belarus   

       user_id traffic_source  
0   b1613cc09f         yandex  
1   4c3ec14bee         direct  
2   a8c40697fb         yandex  
3   521ac1d6a0         yandex  
4   d7323c571c         yandex  
5   fc43898e47         yandex  
6   13fc55e781           paid  
7   cb5082b6f6         direct  
8   45664f7af2         direct  
9   6f9de8c8b6          email  
10  27e76a4a80         direct  
11  3b13701488         google  
12  6d1d81f7f8           paid  
13  7e301c8c41         direct  
14  ac52dedc3b         direct  
15  9a45d98867           paid  
16  e9bd59e22d         google  
17  a2ba8fa3db           paid  
18  72cb10fb5c         direct  
19  7269dcd869         direct

In [40]:
log.loc[log.region == 'Russia'].head()

timestamp    visit_id                                 url  region  \
0  1549980692  e3b0c44298  https://host.ru/3c19b4ef7371864fa3  Russia   
1  1549980704  6e340b9cff  https://host.ru/c8d9213a31839f9a3a  Russia   
2  1549980715  96a296d224  https://host.ru/b8b58337d272ee7b15  Russia   
3  1549980725  709e80c884  https://host.ru/b8b58337d272ee7b15  Russia   
4  1549980736  df3f619804  https://host.ru/b8b58337d272ee7b15  Russia   

      user_id traffic_source  
0  b1613cc09f         yandex  
1  4c3ec14bee         direct  
2  a8c40697fb         yandex  
3  521ac1d6a0         yandex  
4  d7323c571c         yandex